deployment_options <- list(
	#### Do not change anything before this line ####
	deployment_mode = FALSE,
	application_title = "RokaiXplorer-ExampleApp", 
	application_subtitle = "This is a sample application generated by RokaiXplorer", 
	reference_proteome = "Uniprot Mouse", 
	data_file_path = "data/rokaiXplorer_sample_data.csv",
	metadata_file_path = "data/rokaiXplorer_sample_metadata.csv",
	config_file_path = "deploy/config.json", 
	description_file_path = "deploy/description.md", 
	shinyapps_title = NULL,
	shinyapps_account = NULL,
	allow_data_download = TRUE
	#### Do not change anything after this line ####
)

